### PR TITLE
[wagon-ftp] support for secure FTP connection

### PR DESCRIPTION
**Pull request by wiiitek**
Support for secure FTP.

[Build Status](https://travis-ci.org/wiiitek/maven-wagon)

After code changes the configuration could look as follows:

**pom.xml**

```
<project>
    ...
    <distributionManagement>
        ...
        <site>
            <id>ftp.server.id</id>
            <url>ftp://ftp.example.com</url>
        </site>
    </distributionManagement>
    ...
</project>
```

**settings.xml**

```
<settings>
    ...
    <servers>
        ...
        <server>
            <id>ftp.server.id</id>
            <username>username</username>
            <password>password</password>
            <configuration>
                <secure>true</secure>
            </configuration>
        </server>
    </servers>
<settings>
```

See also discussion for related pull request: https://github.com/apache/maven-wagon/pull/22

### CODE REVIEW

**Comment by wiiitek** [comment]
I have created JIRA issue for wagon-ftp secure support: [WAGON-458](https://issues.apache.org/jira/browse/WAGON-458)

**Comment by dantran** [comment]
@wiiitek could you squash the commits?

**Comment by wiiitek** [comment]
Hello @dantran I can squash them. Should I create another pull request with only one commit?

As some time passed I think that the secure FTP client could be chosen based on `ftps:` protocol.
I will create another pull request for that..

**Comment by wiiitek** [comment]
I have created new pull request (with single commit): https://github.com/apache/maven-wagon/pull/30

**Comment by jira-importer** [comment]
Resolve #517

**Pull request closed without merging**
