### PR TITLE
Remove plexus components.xml

### PR DESCRIPTION
**Pull request by elharo**

### CODE REVIEW

**Comment by elharo** [comment]
From assorted test failures, looks like this one might still be used somehow. If so, how? What do we do about that?

Error:    HttpWagonTest>WagonTestCase.runTest:245->WagonTestCase.testWagonPutDirectory:355->WagonTestCase.getWagon:187->PlexusTestCase.lookup:204 » ComponentLookup Component descriptor cannot be found in the component repository
      role: org.apache.maven.wagon.Wagon
  roleHint: http
classRealm: none specified
Error:    HttpWagonTest>WagonTestCase.runTest:245->WagonTestCase.testWagonPutDirectoryDeepDestination:400->WagonTestCase.getWagon:187->PlexusTestCase.lookup:204 » ComponentLookup Component descriptor cannot be found in the component repository
      role: org.apache.maven.wagon.Wagon
  roleHint: http
classRealm: none specified
Error:    HttpWagonTest>WagonTestCase.runTest:245->WagonTestCase.testWagonPutDirectoryForDot:498->WagonTestCase.getWagon:187->PlexusTestCase.lookup:204 » ComponentLookup Component descriptor cannot be found in the component repository
      role: org.apache.maven.wagon.Wagon
  roleHint: http
classRealm: none specified

**Comment by elharo** [comment]
Looks like the Sisu plexus connector does read components.xml if present so the wiki that says we should remove this is not always correct.

**Comment by slachiewicz** [comment]
there is lots of `* @plexus.component role="org.apache.maven.wagon.Wagon" role-hint="file" instantiation-strategy="per-lookup" so this should be migrated first

**Comment by elharo** [comment]
What should it be migrated to? I.e. what's the alternative components.xml? Can I get hold of the injctor somehow and setup a module for Guice? Or maybe it's part of the config for maven-plugin-plugin?

**Pull request closed without merging**
