### PR TITLE
Added support for IPv6 in host par tof url

### PR DESCRIPTION
**Pull request by genadi-hp**
url parsing for host part did not support IPv6 address.

### CODE REVIEW

**Comment by genadi-hp** [comment]
Hi,
Sorry for delay, was at my New Year vacation.
I need additional small clarification: as far as i can see my changes are aligned with current origin/HEAD. 
Do you want me to revert my commits and then add back without changing code style or i can revert code style changes leaving my commits with correct code style. Of cause i will add comments with WAGON-427 prefix.
Thank you and Happy New Year.

**Comment by hboutemy** [comment]
Hi,
Happy New Year to you
Code style change are really the changes that cause harm: if you prefer just revert them, I should find my way.

**Comment by genadi-hp** [comment]
Hi,
I fixed code style to be aligned with common.
And i added prefix WAGON-427 in comments.
Full comment is:
WAGON-427: fixing code style after changes to support IPv6

Have a good year!!!!!

**Comment by genadi-hp** [comment]
Hi,

Do we have any updates? Have you estimations when this fix will be merged?

Thank you in advance

**Comment by hboutemy** [comment]
Hi,

I just applied the modifications
thank you for this improvement and for your patience :)

**Comment by genadi-hp** [comment]
Hi,

Thank you very much, Are you going to close this pull request?

**Comment by hboutemy** [comment]
I didn't add the magic comment in the commit, and I can't close the PR through the web UI (github is ro, since the canonical repo is at Apache)

please close it, since you're the owner

**Pull request closed without merging**
