### PR TITLE
Remove unused class

### PR DESCRIPTION
**Pull request by pzygielo**

### CODE REVIEW

**Comment by pzygielo** [comment]
May I ask for review, please?

**Comment by michael-o** [comment]
Looking into...

**Comment by michael-o** [comment]
I wonder why the class is there, but never used...

**Comment by pzygielo** [comment]
Ping.

**Comment by michael-o** [comment]
Need to understand first why the class is redundant.

**Comment by pzygielo** [comment]
@olamy - could you shed some light on WAGON-350 related changes, please?
For me it looks like code removed in this PR is unused in both commits e248eeea and in next 1f6719c5 (and currently unused too).
(WAGON-350 was closed without fixing, yet plenty of commits refer to it. :confused:)

**Comment by pzygielo** [comment]
Ping.

**Pull request closed without merging**
