### PR TITLE
[WAGON-500] re-enable ScmCvsExeWagonTest

### PR DESCRIPTION
**Pull request by basinilya**

### CODE REVIEW

**Comment by olamy** [comment]
thanks but do we really want spend (waste?) time for cvs :)

**Comment by basinilya** [comment]
At least apply the patches to the java files.

**Comment by basinilya** [comment]
There's a quick and a proper way. The quick way is to return from test methods when no cvs binary is found, just like maven-scm does. I can push the change today.

 The proper way is to migrate to PlexusJUnit4TestCase and use the Assume.assumeTrue() which marks the test as skipped in runtime.

**Comment by michael-o** [comment]
I take either. You decide what you want to provide.

**Comment by basinilya** [comment]
Pushed. Please check.

**Pull request closed without merging**
