### PR TITLE
Support external downloader for downloading files

### PR DESCRIPTION
**Pull request by soiff**
add extension for external downloader by specifying following properties:

```
external.loader=axel
external.filter=.*\\.jar
external.state=.st
```

which means one can download all jar resource through `axel`.

### CODE REVIEW

**Comment by soiff** [comment]
add default filter

**Comment by michael-o** [comment]
Why is `wagon-http` and `wagon-http-lightweight` not enough?

**Comment by soiff** [comment]
It's not enough for unstable network connections and shows not enough log about downloadings, suppose we are behind the GFW. By the way, support external downloaders make wagon itself more flexible. Of course, this patch do not force users to adopt it, which is optional.

**Comment by michael-o** [comment]
If it is not enough for unstable networks, provide PRs to make it bullet-proof. Logs can always we enabled with `-X`  and by tweaking the logging configuration. Still not enough?

**Comment by soiff** [comment]
Yes, you are right. There are no PRs to make it bullet-proof. I've encountered this problem several days ago and I tried this new patch, which solved my problem and it works fine. In my memory, I've blocked for many times when I try to get new releases for artifacts from central repository and it's just waiting without any information print out, which makes me nervous and incomfortable. Of course, nowadays, we use local repository for maven instead of central repository, which reduce this problem too. From my perspective, I just want to make wagon more flexible for users, nothing else.

**Comment by michael-o** [comment]
I do agree, but still think that we can tweak Wagon HTTP to fail faster if such a case happens. Your proxy is likely to use Apache HttpClient, just like Wagon does. You could still suffer from the same problems. I really would like to see this flexibility in a well-established provider which is the default, rather than people having to declare and configure a new one.

**Comment by soiff** [comment]
Actually, `axel` is based on `c` programing language and do really failfast I think. Of course this is not a problem that always happen, which means it would be narrowly needed. After all, improving the default provider should be the more acceptible way. So I'm going to close this comment and post any sugestion if I encountered such problems again. Thanks for your attention!

**Pull request closed without merging**
