### PR TITLE
[WAGON-467] Allow customisation of some SSH options

### PR DESCRIPTION
**Pull request by nfalco79**
This commit add StrictHostKeyChecking and PreferredAuthentications custom fields that together allow you to perform, the command scp enough to remove any user interaction (username, password and add host key to know_hosts file).

### CODE REVIEW

**Comment by dantran** [comment]
@nfalco79, since i used the patch method and push this change. Git cant close this PR. Please close it yourself

**Comment by nfalco79** [comment]
closed by this ffa7fc8830e916e9d3d91a222b641cd5363ffafe

**Comment by dantran** [comment]
@nfalco79 it is a long waited fix.  Thank you and thank you

**Comment by dantran** [comment]
@nfalco79  could you give https://github.com/mojohaus/wagon-maven-plugin/tree/master/src/it/ssh-it  a try?   update the pom to use your env.  I am not able to get mine working.  It always prompts me for host key confirmation

**Comment by dantran** [comment]
confirm it works with maven-site-plugin but not with wagon-maven-plugin

**Comment by nfalco79** [comment]
Follow my settings.xml
{code:xml}
<settings xmlns="http://maven.apache.org/SETTINGS/1.0.0"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://maven.apache.org/SETTINGS/1.0.0
                              https://maven.apache.org/xsd/settings-1.0.0.xsd">
	<servers>
		<server>
			<id>raspberry</id>
			<username>pi</username>
			<password>password</password>
			<configuration>
				<strictHostKeyChecking>no</strictHostKeyChecking>
				<preferredAuthentications>publickey,password</preferredAuthentications>
				<interactive>false</interactive>
			</configuration>
		</server>
	</servers>
</settings>
{code}

I had play with the repository you post.
The reason because your wagon-mave-plugin does not works is because when you instantiate the wagon instance you do not consider the configuration element as the site-plugin does in [AbstractDeployMojo#configureWagon|http://svn.apache.org/viewvc/maven/plugins/tags/maven-site-plugin-3.6/src/main/java/org/apache/maven/plugins/site/deploy/AbstractDeployMojo.java?view=markup#l678] by the XmlPlexusConfiguration

**Comment by nfalco79** [comment]
Debugging a log the issue seems to be which implementation of WagonManger plexus inject. If I run with maven 3.3.9 it injects a [DefaultWagonManager](http://grepcode.com/file/repo1.maven.org/maven2/org.apache.maven/maven-compat/3.3.3/org/apache/maven/repository/legacy/DefaultWagonManager.java#DefaultWagonManager.getWagon%28org.apache.maven.wagon.repository.Repository%29) where the getWagon is deprecated and lacks of configureWagon call that do the trick above. If I run it with maven 2.2.1 it has a working implementation of [DefaultWagonManager](http://grepcode.com/file/repo1.maven.org/maven2/org.apache.maven/maven-artifact-manager/2.2.1/org/apache/maven/artifact/manager/DefaultWagonManager.java#DefaultWagonManager.getWagon%28org.apache.maven.wagon.repository.Repository%29) but mvn command breaks with the following message:
```
[INFO] Unable to initialise extensions
Component descriptor role: 'com.jcraft.jsch.UIKeyboardInteractive', implementation: 'org.apache.maven.wagon.providers.ssh.jsch.interactive.PrompterUIKeyboardInteractive', role hint: 'default' has a hint, but there are other implementations that don't
```
This explains the reason of extra work in the maven-site-plugin around configureWagon method to  distinguish of maven 2/3

I hope these information will help you to make a workaround for your wagon-maven-plugin

**Comment by dantran** [comment]
your patch fixes the site plugin ssh issue.    I will need to implement similar wagon handling developed at maven-site-plugin   https://github.com/mojohaus/wagon-maven-plugin/issues/6

thanks for trouble shooting this

**Comment by jira-importer** [comment]
Resolve #536

**Pull request closed without merging**
